name: e_voting # Nama proyek aplikasi
description: "A new Flutter project." # Deskripsi singkat tentang aplikasi
publish_to: "none" # Tidak mempublikasikan paket ini ke pub.dev
version: 1.0.0+1 # Versi aplikasi, format: major.minor.patch+buildNumber

environment:
  sdk: ">=3.4.3 <4.0.0" # Versi SDK Dart yang digunakan oleh aplikasi

dependencies:
  flutter:
    sdk: flutter # Menggunakan SDK Flutter versi terbaru
  get: ^4.6.6 # Menggunakan GetX versi 4.6.6 untuk manajemen state dan routing
  cupertino_icons: ^1.0.6 # Ikon untuk aplikasi iOS (Cupertino-style)
  dio: ^5.7.0 # Paket untuk melakukan HTTP request dengan lebih mudah dan efisien
  flutter_svg: ^2.0.11 # Paket untuk menampilkan file SVG dalam aplikasi Flutter
  intl: any # Paket internasionalisasi (intl) untuk mendukung format tanggal, waktu, dan angka
  image_picker: ^1.1.2 # Paket untuk memilih gambar dari galeri atau kamera
  shared_preferences: ^2.3.2 # Untuk menyimpan data secara lokal di perangkat

dev_dependencies:
  flutter_test:
    sdk: flutter # Untuk testing aplikasi menggunakan Flutter Test framework
  flutter_lints: ^3.0.0 # Linting (penyaringan) kode untuk memastikan gaya dan kualitas kode

flutter:
  uses-material-design: true # Mengaktifkan material design untuk aplikasi
  assets:
    - assets/icons/ # Menambahkan folder assets/icons untuk menyimpan ikon
    - assets/logo/ # Menambahkan folder assets/logo untuk menyimpan logo
    - assets/images/ # Menambahkan folder assets/images untuk menyimpan gambar lainnya
